import { LiveOrderModel } from './liveorder.model';

export function createEmptyCart(): LiveOrderModel {
  return {
    lines: [],
    lines_sort: [],
    latest_addition: '',
    promocodes: [],
    ismultishipto: false,
    shipmethods: [],
    shipmethod: null,
    addresses: [],
    billaddress: null,
    shipaddress: '',
    paymentmethods: [],
    isPaypalComplete: false,
    touchpoints: {
      logout: '',
      customercenter: '',
      serversync: '',
      viewcart: '',
      login: '',
      welcome: '',
      checkout: '',
      continueshopping: '',
      home: '',
      register: '',
    },
    agreetermcondition: false,
    summary: {
      discounttotal_formatted: '$0.00',
      taxonshipping_formatted: '$0.00',
      taxondiscount_formatted: '$0.00',
      itemcount: 0,
      taxonhandling_formatted: '$0.00',
      total: 0,
      tax2total: 0,
      discountedsubtotal: 0,
      taxtotal: 0,
      discounttotal: 0,
      discountedsubtotal_formatted: '$0.00',
      taxondiscount: 0,
      handlingcost_formatted: '$0.00',
      taxonshipping: 0,
      taxtotal_formatted: '$0.00',
      totalcombinedtaxes_formatted: '$0.00',
      handlingcost: 0,
      totalcombinedtaxes: 0,
      giftcertapplied_formatted: '$0.00',
      shippingcost_formatted: '$0.00',
      discountrate: 0,
      taxonhandling: 0,
      tax2total_formatted: '$0.00',
      discountrate_formatted: '$0.00',
      estimatedshipping: 0,
      subtotal: 0,
      shippingcost: 0,
      estimatedshipping_formatted: '$0.00',
      total_formatted: '$0.00',
      giftcertapplied: 0,
      subtotal_formatted: '$0.00',
    },
    options: {},
  };
}
